default_platform(:ios)

platform :ios do
  lane :upload_testflight do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_KEY_FILEPATH"]
    )
    pilot(
      ipa: ENV["IPA_PATH"],
      skip_waiting_for_build_processing: true
    )
  end
end
